<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Snowdog\Menu\Block\Menu;

/** @var Escaper $escaper */
/** @var Menu $block */
/** @var ViewModelRegistry $viewModels */

$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<?php if ($block->getMenu()): ?>
    <?php
        $parentNode = $block->getParentNode();
        $parentNodeIndex = 'node' . $parentNode->getId();
        $title = $parentNode->getTitle();
    ?>
    <ul x-ref="submenu-<?= /* @noEscape */ (string) $parentNodeIndex ?>"
        class="pb-2 pl-4"
        x-show="isSubmenuOpen"
        x-collapse
        :aria-hidden="!isSubmenuOpen"
        title="<?= $escaper->escapeHtmlAttr($title) ?>"
    >
    <?php if ($block->isViewAllLinkAllowed($parentNode->getType())): ?>
        <li>
            <?= $block->renderViewAllLink($parentNode) ?>
        </li>
    <?php endif; ?>
    <?php foreach ($block->getSubmenuNodes() as $node): ?>
        <?php
            $childrenLevel = $node->getLevel() + 1;
            $children = $block->getNodes($childrenLevel, $node);
            $node->setIsParent((bool)$children);
            $indexId = 'node' . $node->getId();
            $nodeTitle = $node->getTitle();
            $nodeType = $node->getType();
            $nodeClasses = $node->getClasses();
        ?>
            <li class="<?= /* @noEscape */ (string) $nodeType === 'wrapper' ? $escaper->escapeHtmlAttr($nodeClasses) : '' ?>"
                x-data="topmenuMobileItem"
                x-init="init"
                data-nodeid="<?= /* @noEscape */ (string) $indexId ?>"
            >
                <?php if ($node->getIsParent() && !$node->getIsViewAllLink()): ?>
                    <button class="flex items-center justify-between w-full px-8 py-4"
                        @click="toggleSubmenu"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Toggle submenu for %1', $nodeTitle)) ?>"
                        aria-haspopup="true"
                        :aria-expanded="getAriaExpanded"
                        type="button"
                    >
                        <span>
                            <?= $escaper->escapeHtml($nodeTitle) ?>
                        </span>
                        <div class="transition-transform"
                            :class="getButtonClass"
                        >
                            <?= $heroicons->chevronDownHtml('text-gray-500', 20, 20, ['aria-hidden' => 'true']); ?>
                        </div>
                    </button>
                    <?= /* @noEscape */ $block->renderSubmenu($children, $node, $childrenLevel) ?>
                <?php else: ?>
                    <div class="group">
                        <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                    </div>
                <?php endif; ?>
            </li>
        <?php endforeach ?>
    </ul>
<?php endif; ?>

