<?php
namespace Snowdog\Menu\Model\ResourceModel\Menu\Node;

use Magento\Framework\DB\Sql\Expression;
use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;

class Collection extends AbstractCollection
{
    protected function _construct()
    {
        $this->_init(
            \Snowdog\Menu\Model\Menu\Node::class,
            \Snowdog\Menu\Model\ResourceModel\Menu\Node::class
        );
    }

    protected function _initSelect()
    {
        parent::_initSelect(); // TODO: Change the autogenerated stub
        $this->getSelect()->joinLeft(
            ['customer' => 'snowmenu_customer'],
            'main_table.node_id = customer.node_id',
            ['customer_groups' => new Expression('GROUP_CONCAT(group_id SEPARATOR \',\')')]
        )->group('main_table.node_id');
//        die ((string) $collection->getSelect());
    }
}
