<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php $menuClass = $block->getMenu()->getCssClass() ?>
<div class="<?= $menuClass ?>__mobile">
    <svg title="icon-arrow-down" class="<?= $menuClass ?>__mobile-icon">
        <use xlink:href="<?= $block->getViewFileUrl('images/icon-sprite.svg#icon-mobile-menu'); ?>"></use>
    </svg>
</div>
<nav class="<?= $menuClass ?>">
    <ul class="<?= $menuClass ?>__list" data-mage-init='{ "navigationMenu": {} }'>
        <?php foreach ($block->getNodes() as $node): ?>
            <?php
                $children = $this->getNodes($node->getLevel() + 1, $node);
                $parentClass = $children ? '--parent' : '';
            ?>
            <li class="<?= $menuClass ?>__item<?= $parentClass ?>">
                <?php echo $block->renderMenuNode($node) ?>
                <?php echo $block->renderSubmenu($children, $node->getNodeId()) ?>
            </li>
        <?php endforeach ?>
    </ul>
    <div class="<?= $menuClass ?>__mobile-bg"></div>
</nav>
