<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<div class="menu__mobile">
    <svg title="icon-arrow-down" class="menu__mobile-icon">
        <use xlink:href="<?= $block->getViewFileUrl('images/icon-sprite.svg#icon-mobile-menu'); ?>"></use>
    </svg>
</div>
<nav class="menu">
    <ul class="menu__list"
        data-mage-init='{ "navigationMenu": {} }'
    >
        <?php
            /**
             * Render child menus
             *
             * @param \Snowdog\Menu\Block\Menu $block
             * @param array $subList
             * @param int $listLevel
             * @return string
             */
            function renderSnowdogMenuSubList(\Snowdog\Menu\Block\Menu $block, array $subList, int $listLevel)
            {
                $wrapperLevelClass = 'menu__inner-list--level' . $listLevel;
                $wrapperClass = 'menu__inner-list ' . $wrapperLevelClass;
                $itemLevelClass = 'menu__inner-item--level' . $listLevel;
                $parentItemClass = 'menu__inner-item--parent';
                $itemBaseClass = 'menu__inner-item ' . $itemLevelClass;
                $itemLinkClass = 'menu__inner-link';

                $html = '<ul class="' . $wrapperClass . '">';

                foreach ($subList as $item) {
                    $node = $item['node'];
                    $itemClass = $itemBaseClass . ' ' . $node->getClasses();

                    if ($item['children']) {
                        $itemClass .= ' ' . $parentItemClass;
                    }

                    $html .= '<li class="' . $itemClass . '">';

                    switch ($node->getType()) {
                        case 'category':
                            $categoryUrl = $block->getNodeTypeProvider($node->getType())
                                ->getCategoryUrl($node->getNodeId());

                            $html .= '<a href="' . $categoryUrl
                                   . '" class="' . $itemLinkClass
                                   . '">' . $node->getTitle() . '</a>';
                            break;
                        case 'cms_block':
                            $html .= $block->getNodeTypeProvider($node->getType())
                                ->getHtml($node->getNodeId(), $listLevel);
                            break;
                        default:
                            $html .= $node->getContent();
                    }

                    if ($item['children']) {
                        $html .= renderSnowdogMenuSubList($item['children'], $listLevel + 1);
                    }

                    $html .= '</li>';
                }

                $html .= '</ul>';

                return $html;
            }
        ?>

        <?php foreach ($this->getNodesTree() as $item): ?>
            <?php
                $node = $item['node'];
                $itemParentClass = $item['children'] ? 'menu__item--parent' : '';
                $itemLinkUrl = '';

                switch ($node->getType()) {
                    case 'category':
                        $itemLinkUrl = $this->getNodeTypeProvider($node->getType())
                            ->getCategoryUrl($node->getNodeId());
                        break;
                    case 'custom_url':
                        $itemLinkUrl = $node->getContent();
                        break;
                }
            ?>

            <li class="menu__item <?= $itemParentClass ?> <?= $node->getClasses() ?>">
                <?php if ($itemLinkUrl): ?>
                    <a href="<?= $itemLinkUrl ?>" class="menu__link">
                        <?= $node->getTitle() ?>
                    </a>
                <?php elseif ($node->getType() == 'cms_block'): ?>
                    <div class="menu__link">
                        <?= $this->getNodeTypeProvider($node->getType())->getHtml($node->getNodeId(), $listLevel) ?>
                    </div>
                <?php else: ?>
                    <?= $node->getContent() ?>
                <?php endif ?>
                <?php
                    if ($item['children']) {
                        echo renderSnowdogMenuSubList($block, $item['children'], $node->getLevel() + 1);
                    }
                ?>
            </li>
        <?php endforeach ?>
    </ul>
    <div class="menu__mobile-bg"></div>
</nav>
