<?php
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Snowdog\Menu\Block\Menu;
use Hyva\Theme\ViewModel\HyvaCsp;

/** @var Escaper $escaper */
/** @var Menu $block */
/** @var HeroiconsOutline $heroicons */
/** @var ViewModelRegistry $viewModels */

$menu = $block->getMenu();
$uniqueId = '_' . uniqid();

$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<?php if ($menu): ?>
    <div
        class="
            <?= $escaper->escapeHtmlAttr($menu->getCssClass()) ?>
            snowdog-menu-footer w-full flex flex-wrap text-primary-darker
        "
        x-data="footerMenu"
        x-init="init"
        @resize.window.debounce="onResize"
        @visibilitychange.window.debounce="onVisibilityChange"
    >
        <ul class="w-full flex flex-col flex-wrap lg:flex-row lg:justify-between lg:gap-6 divide-y divide-container lg:divide-y-0">
            <?php foreach ($block->getNodes() as $key => $node): ?>
                <?php
                $childrenLevel = $node->getLevel() + 1;
                $children = $block->getNodes($childrenLevel, $node);
                $node->setIsParent((bool) $children);
                $indexId = 'node' . $node->getId();
                $title = $node->getTitle();
                $nodeType = $node->getType();
                $nodeClasses = $node->getClasses();
            ?>
                <li x-data="footerMenuItem"
                    x-init="init"
                    data-indexid="<?= /* @noEscape */ (string) $indexId ?>"
                    class="flex-1"
                >
                    <?php if ($node->getIsParent() && !$node->getIsViewAllLink()): ?>
                        <div @keydown.escape="onEscape">
                            <span x-show="isDesktop"
                                x-cloak="tablet"
                                class="block font-bold mb-6"
                            >
                                <?= $escaper->escapeHtml($title) ?>
                            </span>
                            <button
                                x-show="!isDesktop"
                                x-cloak="desktop"
                                x-ref="submenu-toggle-<?= /* @noEscape */ (string) $indexId ?>"
                                class="
                                    w-full py-4 font-bold
                                "
                                @click="onClick"
                                :aria-expanded="getAriaExpanded"
                                type="button"
                            >
                                <div class="flex items-center justify-between">
                                    <span>
                                        <?= $escaper->escapeHtml($title) ?>
                                    </span>
                                    <div class="transition-transform"
                                        :class="getIconClass"
                                    >
                                        <?= $heroicons->chevronDownHtml('text-gray-500', 20, 20, ['aria-hidden' => 'true']); ?>
                                    </div>
                                </div>
                            </button>
                            <div x-show="showSubmenu"
                                x-cloak="tablet"
                                x-ref="submenu-<?= /* @noEscape */ (string) $indexId ?>"
                                x-collapse
                                class="pb-2"
                                :aria-hidden="getAriaHidden"
                            >
                                <?= /* @noEscape */ $block->renderSubmenu($children, $node, $childrenLevel) ?>
                            </div>
                        </div>
                    <?php else: ?>
                        <div class="group">
                            <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                        </div>
                    <?php endif; ?>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
<?php endif; ?>
