<?php
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Snowdog\Menu\Block\Menu;

/** @var Escaper $escaper */
/** @var Menu $block */
/** @var ViewModelRegistry $viewModels */

$heroicons = $viewModels->require(HeroiconsOutline::class);

$menu = $block->getMenu();
?>

<?php if ($menu): ?>
    <nav
        class="
            <?= $escaper->escapeHtmlAttr($menu->getCssClass()) ?>
            snowdog-topmenu-mobile z-20 order-2 text-primary-darker sm:order-1 navigation lg:hidden
        "
        x-data="topmenuMobile"
        @keydown.escape="closeMenu"
        @click.outside="closeMenu"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
        role="navigation"
    >
        <button x-ref="open-menu-button"
            @click="openMenu"
            type="button"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
            :aria-expanded="open"
            aria-haspopup="menu"
        >
            <?= $heroicons->menuHtml('', 24, 24, ['aria-hidden' => 'true']) ?>
        </button>
        <div class="backdrop z-30"
            x-show="open"
            x-transition:enter="ease-in-out duration-500"
            x-transition:enter-start="opacity-0"
            x-transition:enter-end="opacity-100"
            x-transition:leave="ease-in-out duration-500"
            x-transition:leave-start="opacity-100"
            x-transition:leave-end="opacity-0"
            @click="closeMenu"
            x-cloak
        ></div>
        <div class="fixed z-30 top-0 left-0 w-full max-w-lg h-full bg-container-lighter border-container overflow-y-auto overflow-x-hidden transform transition ease-in-out duration-500 sm:duration-700"
            :class="getMenuClass"
            x-cloak
            x-ref="menu-dialog"
            role="dialog"
            aria-modal="true"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
            :inert="isClosed"
        >
            <div x-show="open"
                class="flex flex-col-reverse"
            >
                <ul class="mb-1 divide-y divide-container">
                    <?php foreach ($block->getNodes() as $node): ?>
                        <?php
                            $childrenLevel = $node->getLevel() + 1;
                            $children = $block->getNodes($childrenLevel, $node);
                            $node->setIsParent((bool)$children);
                            $indexId = 'node' . $node->getId();
                            $title = $node->getTitle();
                            $nodeType = $node->getType();
                            $nodeClasses = $node->getClasses();
                        ?>
                        <li x-data="topmenuMobileItem"
                            x-init="init"
                            data-nodeid="<?= /* @noEscape */ (string) $indexId ?>"
                            class="<?= /* @noEscape */ (string) $nodeType === 'wrapper' ? $escaper->escapeHtmlAttr($nodeClasses) : '' ?>"
                        >
                            <?php if ($node->getIsParent() && !$node->getIsViewAllLink()): ?>
                                <button
                                    class="flex items-center justify-between w-full px-8 py-4"
                                    @click="toggleSubmenu"
                                    aria-label="<?= $escaper->escapeHtmlAttr(__('Toggle submenu for %1', $title)) ?>"
                                    :aria-expanded="getAriaExpanded"
                                    type="button"
                                >
                                    <span>
                                        <?= $escaper->escapeHtml($title) ?>
                                    </span>
                                    <div class="transition-transform"
                                        :class="getButtonClass"
                                    >
                                        <?= $heroicons->chevronDownHtml('text-gray-500', 20, 20, ['aria-hidden' => 'true']); ?>
                                    </div>
                                </button>
                                <?= /* @noEscape */ $block->renderSubmenu($children, $node, $childrenLevel) ?>
                            <?php else: ?>
                                <div class="group">
                                    <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                                </div>
                            <?php endif; ?>
                        </li>
                    <?php endforeach ?>
                </ul>
                <div class="flex justify-end px-3 border-b border-container">
                    <button
                        @click="closeMenu"
                        class="flex justify-center items-center w-16 h-16"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
                        type="button"
                    >
                        <?= $heroicons->xHtml('', 24, 24, ["aria-hidden" => "true"]) ?>
                    </button>
                </div>
            </div>
        </div>
    </nav>
<?php endif; ?>
