<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php if ($block->getMenu()): ?>
    <?php
    $menuClass = $block->getMenu()->getCssClass();
    $parentNode = $block->getParentNode();
    $level = $block->getLevel();
    $title = $parentNode->getTitle();
    ?>
    <ul title="<?= $escaper->escapeHtmlAttr($title) ?>">
        <?php foreach ($block->getSubmenuNodes() as $node): ?>
            <?php
            $childrenLevel = $node->getLevel() + 1;
            $children = $block->getNodes($childrenLevel, $node);
            $node->setIsParent((bool) $children);
            $nodeType = $node->getType();
            $nodeClasses = $node->getClasses();
            ?>
            <li :class="{
                    '<?= $escaper->escapeHtmlAttr($nodeClasses) ?>' : '<?= /* @noEscape */ (string) $nodeType ?>' === 'wrapper',
                }"
            >
                <div class="group"
                    :class="{
                        '<?= $escaper->escapeHtmlAttr($nodeClasses) ?>' : '<?= /* @noEscape */ (string) $nodeType ?>' !== 'wrapper'
                    }"
                >
                    <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                </div>
                <?= $block->renderSubmenu($children, $node, $childrenLevel) ?>
            </li>
        <?php endforeach ?>
    </ul>
<?php endif; ?>
