<?php /** @var $block \Snowdog\Menu\Block\NodeType\Category */ ?>
<div class="admin__field field field-title"
     data-mage-init='<?= str_replace('\'', '', $block->getJsonConfig()) ?>'
>
    <label class="label admin__field-label">
        <?= __('Category') ?>
    </label>
    <div class="admin__field-control control autocomplete_container">
        <input class="input-text admin__control-text" type="text"/>
    </div>
    <div class="selected-option">
      <p class="selected-option__label">
        Category ID
      </p>
      <p class="selected-option__value"></p>
    </div>
</div>
