<?php /** @var $block \Snowdog\Menu\Block\NodeType\CmsPage */ ?>
<div class="admin__field field field-title">
    <label class="label admin__field-label" for="cms_page_identifier"><?= __('Page Name'); ?></label>
    <div class="admin__field-control control node-value-field">
        <input class="input-text admin__control-text" id="cms_page_identifier" type="text"/>
    </div>
    <span class="label"></span>
</div>