<?php /** @var $block \Snowdog\Menu\Block\NodeType\CmsBlock */ ?>
<div class="admin__field field field-title" data-mage-init='<?= str_replace('\'', '', $block->getJsonConfig()) ?>'>
    <label class="label admin__field-label" for="cms_block_identifier">Block Title</label>
    <div class="admin__field-control control">
        <input class="input-text admin__control-text" id="cms_block_identifier" type="text"/>
    </div>
    <span class="label"></span>
</div>