<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php if ($block->getMenu()): ?>
    <?php
    $menuClass = $block->getMenu()->getCssClass();
    $parentNode = $block->getParentNode();
    $level = $block->getLevel();
    $title = $parentNode->getTitle();
    ?>
    <ul class="space-y-2"
        title="<?= $escaper->escapeHtmlAttr($title) ?>"
    >
        <?php foreach ($block->getSubmenuNodes() as $node): ?>
            <?php
            $childrenLevel = $node->getLevel() + 1;
            $children = $block->getNodes($childrenLevel, $node);
            $node->setIsParent((bool) $children);
            $nodeType = $node->getType();
            $nodeClasses = $node->getClasses();
            ?>
            <li class="<?= /* @noEscape */ (string) $nodeType === 'wrapper' ? $escaper->escapeHtmlAttr($nodeClasses) : '' ?>">
                <div class="group">
                    <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                </div>
                <?= $block->renderSubmenu($children, $node, $childrenLevel) ?>
            </li>
        <?php endforeach ?>
    </ul>
<?php endif; ?>
