<?php /** @var \Snowdog\Menu\Block\Menu $block */ ?>
<?php
$menuClass = $block->getMenu()->getCssClass();
$level = $block->getLevel();
?>
<ul class="<?= $menuClass ?>__inner-list <?= $menuClass ?>__inner-list--level<?= $level ?>" data-menu="menu-<?= $block->getParentNodeId() ?>">
    <?php foreach ($block->getSubmenuNodes() as $node): ?>
        <?php
            $childrenLevel = $node->getLevel() + 1;
            $children = $this->getNodes($childrenLevel, $node);
            $node->setIsParent((bool) $children);
            $parentClass = $children ? ' ' . $menuClass . '__inner-item--parent' : '';
            $additionalClasses = $node->getClasses() ? ' ' . $node->getClasses() : '';
            $itemClasses = $parentClass . $additionalClasses;
        ?>
        <?php if ($children && $block->isViewAllLinkAllowed($node->getType())): ?>
            <li class="<?= $menuClass ?>__inner-item <?= $menuClass ?>__inner-item--all <?= $menuClass ?>__inner-item--level<?= $level ?>">
                <?php echo $block->renderViewAllLink($node) ?>
            </li>
        <?php endif ?>
        <li class="<?= $menuClass ?>__inner-item <?= $menuClass ?>__inner-item--level<?= $level ?><?= $itemClasses ?>">
            <?php echo $block->renderMenuNode($node) ?>
            <?php echo $block->renderSubmenu($children, $node->getNodeId(), $childrenLevel) ?>
        </li>
    <?php endforeach ?>
</ul>
