<?php
/** @var Product $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Snowdog\Menu\Block\NodeType\Product;

?>
<?php
$nodeId = $block->getId();
$productUrl = $block->getProductUrl($nodeId);
$imageSize = '300';
$resizedProductImage = $block->getResizedProductImage($nodeId, $imageSize, $imageSize);
$productUrl = $productUrl ?: '#';
$title = $block->getTitle();
$imageAltText = $block->getImageAltText();
$nodeClasses = $block->getNodeClasses();
?>

<?php if ($resizedProductImage): ?>
    <a
        href="<?= $escaper->escapeUrl($productUrl) ?>"
        class="block mb-2 transition-opacity group-hover:opacity-80 "
        tabindex="-1"
    >
        <img src="<?= $escaper->escapeUrl($resizedProductImage) ?>"
            alt="<?= $escaper->escapeHtmlAttr($imageAltText) ?>"
            loading="lazy"
            width="<?= $escaper->escapeHtmlAttr($imageSize) ?>"
            height="<?= $escaper->escapeHtmlAttr($imageSize) ?>"
        />
    </a>
<?php endif; ?>
<a
    href="<?= $escaper->escapeUrl($productUrl) ?>"
    class="snowdog-menu-link <?= $escaper->escapeHtmlAttr($nodeClasses) ?>"
    <?php if ($nodeId): ?>
        data-menu="menu-<?= $escaper->escapeHtmlAttr($nodeId) ?>"
    <?php endif; ?>
>
    <?= $escaper->escapeHtml($title) ?>
</a>
