<?php
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Snowdog\Menu\Block\Menu;

/** @var Menu $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$menu = $block->getMenu();
$uniqueId = '_' . uniqid();
?>

<?php if ($menu): ?>
    <div x-data="topmenuDesktop"
        class="
            <?= $escaper->escapeHtmlAttr($menu->getCssClass()) ?>
            navigation hidden w-full bg-container-darker lg:block
        "
    >
        <nav
            class="snowdog-topmenu-desktop container lg:block"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
        >
            <ul
                class="relative flex justify-between h-20"
                @mouseleave="closeSubmenu"
            >
                <?php foreach ($block->getNodes() as $node): ?>
                    <?php
                    $childrenLevel = $node->getLevel() + 1;
                    $children = $block->getNodes($childrenLevel, $node);
                    $node->setIsParent((bool) $children);
                    $additionalClasses = $node->getClasses() ? ' ' . $node->getClasses() : '';
                    $nodeId = $node->getId();
                    $title = $node->getTitle();
                    $nodeType = $node->getType();
                    $nodeClasses = $node->getClasses();
                    ?>
                    <li x-data="topmenuDesktopItem"
                        x-init="init"
                        data-nodeid="<?= /* @noEscape */ (string) $nodeId ?>"
                        data-haschildren="<?= /* @noEscape */ !!$children ? 'true' : 'false' ?>"
                        class="
                            flex items-center justify-between px-6
                            <?= /* @noEscape */ (string) $nodeType === 'wrapper' ? $escaper->escapeHtmlAttr($nodeClasses) : '' ?>
                        "
                        :class="getItemClass"
                        @mouseenter="openSubmenu"
                        @keydown.escape="onSubmenuEscape"
                    >
                        <div class="group uppercase [&>a]:py-7 [&>a]:!text-primary">
                            <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                        </div>
                        <?php if ($children): ?>
                            <div class="relative">
                                <button
                                    type="button"
                                    class="flex items-center ml-2 transition-transform duration-300"
                                    :class="getButtonClass"
                                    x-ref="sr-button-<?= /* @noEscape */ (string) $nodeId ?>"
                                    :aria-expanded="getAriaExpanded"
                                    @click="toggleSubmenu"
                                >
                                    <?= $heroiconsSolid->chevronDownHtml('text-primary-darker', 20, 20, ['aria-hidden' => 'true']) ?>
                                    <span class="sr-only">
                                        <?= $escaper->escapeHtml(__('Toggle submenu for %1', $title)) ?>
                                    </span>
                                </button>
                            </div>
                        <?php endif; ?>
                        <?= /* @noEscape */ $block->renderSubmenu($children, $node, $childrenLevel) ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>
    </div>
<?php endif; ?>
