<?php /** @var $block \Snowdog\Menu\Block\Menu\Edit\Tab\Nodes */ ?>
<div>
    <div data-mage-init='{"snowMenuEditorInit":{}}' id="snowmenu_tree_container">
        <?= $block->renderNodes() ?>
    </div>
    <div data-mage-init='{"snowMenuEditorAdd":{}}' class="node-buttons-container">
        <?php foreach ($block->getNodeButtons() as $code => $label): ?>
            <button id="add-<?= $code ?>" data-type="<?= $code ?>"><?= $label ?></button>
        <?php endforeach ?>
    </div>
    <div>
        <label for="snowmenu-node-name"><?= __('Node name') ?></label>
        <input data-mage-init='{"snowMenuEditorRename":{}}' id="snowmenu-node-name" type="text"/>
    </div>
    <?php foreach ($block->getNodeForms() as $form): ?>
        <?= $form->toHtml() ?>
    <?php endforeach ?>
    <textarea name="serialized_nodes" data-mage-init='{"snowMenuEditorSerialize":{}}' rows="20" cols="200"></textarea>
</div>
