<?php
/** @var \Snowdog\Menu\Block\NodeType\AbstractNode $form */
$fieldData = [];
foreach ($block->getNodeForms() as $form) {
    $fieldData[$form->getNodeType()] = $form->getJsonConfig();
}

// TODO: backend - create method to return array of nodes components
// https://github.com/SnowdogApps/magento2-menu/issues/69#issuecomment-443500749
$vueComponents = [
    "vue!Snowdog_Menu/vue/menu-type/category",
    "vue!Snowdog_Menu/vue/menu-type/cms-page",
    "vue!Snowdog_Menu/vue/menu-type/cms-block",
    "vue!Snowdog_Menu/vue/menu-type/custom-url",
    "vue!Snowdog_Menu/vue/menu-type/product",
    "vue!Snowdog_Menu/vue/menu-type/wrapper",
];

?>

<div id="snowdog_menu">
    <snowdog-menu :list="list" :config="config">
        <div class="panel__loader">
            <div class="spinner">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </snowdog-menu>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "menuNodes": {
                "vueComponents": <?= json_encode($vueComponents) ?>,
                "data": {
                    "list"  : <?= json_encode($block->renderNodes()) ?>,
                    "config": {
                        "fieldData"  : <?= json_encode($fieldData) ?>,
                        "nodeTypes"  : <?= json_encode($block->getNodeLabels()) ?>,
                        "translation": {
                            "nodes"          : "<?= __('Nodes') ?>",
                            "click"          : "<?= __('Click') ?>",
                            "createFirstNode": "<?= __('to create your first node.') ?>",
                            "createSubNode"  : "<?= __('to create sub node or drag and drop other nodes here.') ?>",
                            "append"         : "<?= __('Append') ?>",
                            "edit"           : "<?= __('Edit') ?>",
                            "delete"         : "<?= __('Delete') ?>",
                            "addNode"        : "<?= __('New node') ?>",
                            "nodeType"       : "<?= __('Node Type') ?>",
                            "nodeName"       : "<?= __('Node name') ?>",
                            "nodeClasses"    : "<?= __('Node CSS classes') ?>",
                            "selectNodeType" : "<?= __('Select Node Type') ?>",
                            "pleaseSelect"   : "<?= __('Please select a') ?>",
                            "targetLabel"    : "<?= __('Node target blank') ?>",
                            "category"       : "<?= __('Category') ?>",
                            "categoryId"     : "<?= __('Category ID') ?>",
                            "block"          : "<?= __('Block') ?>",
                            "blockId"        : "<?= __('Block ID') ?>",
                            "page"           : "<?= __('Page') ?>",
                            "pageId"         : "<?= __('Page URL key') ?>",
                            "customURL"      : "<?= __('Custom URL') ?>",
                            "product"        : "<?= __('Product') ?>",
                            "productId"      : "<?= __('Product ID') ?>"
                        }
                    }
                }
            }
        }
    }
</script>
