<?php /** @var $block \Snowdog\Menu\Block\Menu\Edit\Tab\Nodes */ ?>
<fieldset class="fieldset admin__fieldset fieldset-wide snowdog-tree-menu-editor"
          id="menu_tree_editor"
>
    <div class="admin__field field field-title"
         data-mage-init='{"snowMenuEditorInit":{}}'
         id="snowmenu_tree_container"
    >
        <?= $block->renderNodes() ?>
    </div>

    <div class="admin__field field field-title">
        <div class="node-buttons-container__row">
            <div class="node-buttons-container__add"
                 data-mage-init='{"snowMenuEditorAdd":{}}'
            >
                <select class="admin__control-select"
                        name="node_type"
                        id="node_type"
                >
                    <option value="">
                        <?= __('Select Node Type') ?>
                    </option>
                    <?php foreach ($block->getNodeButtons() as $code => $label): ?>
                        <option value="<?= $code ?>">
                            <?= $label ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <button class="
                            primary
                            node-buttons-container__button
                            node-buttons-container__button--add
                        "
                        type="button"
                        id="snowmenu_tree_add"
                        disabled
                >
                    <?= __('Add') ?>
                </button>
            </div>
            <button class="
                        secondary
                        node-buttons-container__button
                        node-buttons-container__button--delete
                    "
                    type="button"
                    data-mage-init='{"snowMenuEditorDelete":{}}'
            >
                <?= __('Delete selected node') ?>
            </button>
        </div>
    </div>

    <?php /** @var \Snowdog\Menu\Block\NodeType\AbstractNode $form */ ?>
    <?php foreach ($block->getNodeForms() as $form): ?>
        <fieldset class="fieldset fieldset-<?= $form->getNodeType(); ?> admin__fieldset fieldset-wide"
                data-mage-init='<?= str_replace('\'', '', $form->getJsonConfig()); ?>'
                data-node-type="<?= $form->getNodeType(); ?>"
        >
            <?php foreach ($form->getNodeAttributes() as $formAttribute): ?>
                <div class="admin__field field field-title">
                    <label class="label admin__field-label" for="snowmenu_<?= $formAttribute->getId(); ?>">
                        <?= __($formAttribute->getLabel()); ?>
                    </label>

                    <div class="admin__field-control control">
                        <?php if ($formAttribute->getType() === 'wysiwyg'): ?>
                            <?php
                            $wysiwyg = $block->getEditor('snowmenu_' . $formAttribute->getId(), $formAttribute->getId());
                            $wysiwyg->setDataMageInit(
                                '{"snowMenuEditorRename":{"type":"' . $formAttribute->getCode() . '"}}'
                            );
                            echo $wysiwyg->getElementHtml();
                            ?>
                        <?php elseif ($formAttribute->getType() === 'checkbox'): ?>
                            <input class="checkbox"
                                   data-mage-init='{"snowMenuEditorRename":{"type":"<?= $formAttribute->getCode(); ?>"}}'
                                   id="snowmenu_<?= $formAttribute->getId(); ?>"
                                   type="<?= $formAttribute->getType(); ?>"
                            />
                        <?php else: ?>
                            <input class="input-text admin__control-text"
                                   data-mage-init='{"snowMenuEditorRename":{"type":"<?= $formAttribute->getCode(); ?>"}}'
                                   id="snowmenu_<?= $formAttribute->getId(); ?>"
                                   type="<?= $formAttribute->getType(); ?>"
                            />
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
            <?= $form->toHtml(); ?>
        </fieldset>
    <?php endforeach; ?>

    <input type="hidden"
           name="serialized_nodes"
           id="serialized_nodes"
           data-mage-init='{"snowMenuEditorSerialize":{}}'
    />
</fieldset>
