<?php
/** @var Snowdog\Menu\Block\NodeType\CategoryChild $block */
$visibleChildren = $block->getVisibleChildren();
$nodeId = $block->getId();
?>

<ul class="<?= $escaper->escapeHtmlAttr($block->getNodeClasses()) ?>"
    <?php if ($nodeId) : ?>
        data-menu="menu-<?= $escaper->escapeHtmlAttr($nodeId) ?>"
    <?php endif; ?>
>
    <?php foreach ($visibleChildren as $child): ?>
        <li>
            <a
                class="snowdog-menu-link-topmenu-mobile"
                href="<?= $escaper->escapeUrl($child->getUrl()) ?>"
            >
                <?= $escaper->escapeHtml($child->getName()) ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
