<?php
/** @var CmsPage $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Snowdog\Menu\Block\NodeType\CmsPage;

?>
<?php
$nodeId = $block->getId();
$pageUrl = $block->getPageUrl($nodeId) ?: '#';
$imageUrl = $block->getImageUrl();
$imageAltText = $block->getImageAltText();
$imageWidth = $block->getImageWidth();
$imageHeight = $block->getImageHeight();
$title = $block->getTitle();
$nodeClasses = $block->getNodeClasses();
?>

<?php if ($imageUrl): ?>
    <a href="<?= $escaper->escapeUrl($pageUrl) ?>"
        class="block mb-2 transition-opacity group-hover:opacity-80"
        tabindex="-1"
    >
        <img
            src="<?= $escaper->escapeUrl($imageUrl) ?>"
            alt="<?= $escaper->escapeHtmlAttr($imageAltText) ?>"
            loading="lazy"
            width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>"
            height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>"
        />
    </a>
<?php endif; ?>
<a class="snowdog-menu-link-topmenu-mobile <?= $escaper->escapeHtmlAttr($nodeClasses) ?>"
    href="<?= $escaper->escapeUrl($pageUrl) ?>"
    <?php if ($nodeId): ?>
        data-menu="menu-<?= $escaper->escapeHtmlAttr($nodeId) ?>"
    <?php endif; ?>
>
    <?= $escaper->escapeHtml($title) ?>
</a>
