<?php
/** @var Product $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Snowdog\Menu\Block\NodeType\Product;

?>
<?php
$nodeId = $block->getId();
$productUrl = $block->getProductUrl($nodeId);
$productUrl = $productUrl ?: '#';
$title = $block->getTitle();
$nodeClasses = $block->getNodeClasses();
?>

<a class="cursor-pointer snowdog-menu-link-topmenu-mobile <?= $escaper->escapeHtmlAttr($nodeClasses) ?>"
    href="<?= $escaper->escapeUrl($productUrl) ?>"
    <?php if ($nodeId): ?>
        data-menu="menu-<?= $escaper->escapeHtmlAttr($nodeId) ?>"
    <?php endif; ?>
>
    <?= $escaper->escapeHtml($title) ?>
</a>
