<?php /** @var \Snowdog\Menu\Block\NodeType\Product $block */ ?>
<?php
$nodeId = $block->getId();
$productUrl = $block->getProductUrl($nodeId);
$productPrice = $block->getProductPrice($nodeId);
$formattedProductPrice = $block->getFormattedProductPrice($nodeId);
$productImage = $block->getProductImage($nodeId);
$resizedProductImage = $block->getResizedProductImage($nodeId, '300', '300');
$productTitle = $block->getProductTitle($nodeId);
$productUrl = $productUrl ?: '#';
$title = $block->getTitle();
$imageUrl = $block->getImageUrl();
$imageAltText = $block->getImageAltText();
$nodeClasses = $block->getNodeClasses();
?>

<a class="cursor-pointer snowdog-menu-link-topmenu-mobile <?= $escaper->escapeHtmlAttr($nodeClasses) ?>"
    href="<?= $escaper->escapeUrl($productUrl) ?>"
    <?php if ($nodeId) : ?>
        data-menu="menu-<?= $escaper->escapeHtmlAttr($nodeId) ?>"
    <?php endif; ?>
>
    <?= $escaper->escapeHtml($title) ?>
</a>
