<?php /** @var \Snowdog\Menu\Block\NodeType\Category $block */ ?>
<?php
$nodeId = $block->getId();
$class = $block->getMenuClass();
$categoryUrl = $block->getCategoryUrl($nodeId);
$categoryUrl = $categoryUrl ?: '#';
$dataAttribute = '';

if ($block->getIsViewAllLink()) {
    $title = __('View All');
    $class .= '__inner-link';
} else {
    $class .= $block->getIsRoot() ? '__link' : '__inner-link';
    $title = $block->getTitle();
    if ($nodeId) {
        $dataAttribute = ' data-menu="menu-' . $nodeId . '"';
    }
}
?>
<a href="<?= $categoryUrl ?>"
   class="<?= $class ?>"<?= $dataAttribute ?>
>
    <?= $title ?>
</a>
