<?php /** @var \Snowdog\Menu\Block\NodeType\Category $block */ ?>
<?php
$nodeId = $block->getId();
$class = $block->getMenuClass();
$categoryUrl = $block->getCategoryUrl($nodeId);
$categoryUrl = $categoryUrl ?: '#';
$nodeLevel = $block->getLevel() + 1;
$dataAttribute = '';

if ($block->getIsViewAllLink()) {
    $title = __('View All');
    $classLink = $class . '__inner-link';
} else {
    $classLink = $block->getIsRoot() ? $class . '__link' : $class . '__inner-link';
    $title = $block->getTitle();

    if ($nodeId) {
        $dataAttribute = ' data-menu="menu-' . $nodeId . '"';
    }

    if ($block->isCurrentCategory($nodeId)) {
        $class .= ' current';
    }
}
?>
<a href="<?= $categoryUrl ?>"
   class="<?= $classLink ?>"<?= $dataAttribute ?>
>
    <?= $title ?>
    <?php if ($block->getIsParent() && !$block->getIsViewAllLink()): ?>
        <?php if ($nodeLevel == 1): ?>
            <svg title="view more" class="<?= $class ?>__icon">
                <use xlink:href="<?= $block->getViewFileUrl('Snowdog_Menu::images/menu-icon-sprite.svg#icon-arrow-down') ?>"></use>
            </svg>
        <?php elseif ($nodeLevel != 1): ?>
            <svg title="view more" class="<?= $class ?>__icon <?= $class ?>__icon--inner">
                <use xlink:href="<?= $block->getViewFileUrl('Snowdog_Menu::images/menu-icon-sprite.svg#icon-plus') ?>"></use>
            </svg>
        <?php endif ?>
    <?php endif ?>
</a>
