<?php /** @var \Snowdog\Menu\Block\NodeType\CmsPage $block */ ?>
<?php
$class = $block->getMenuClass();
$dataAttribute = '';

if ($block->getIsViewAllLink()) {
    $title = __('View All');
    $class .= '__inner-link';
} else {
    $class .= $block->getIsRoot() ? '__link' : '__inner-link';
    $title = $block->getTitle();
    if ($block->getId()) {
        $dataAttribute = ' data-menu="menu-' . $block->getId() . '"';
    }
}
?>
<a href="<?= $block->getContent() ?>"
   class="<?= $class ?>"<?= $dataAttribute ?>
>
    <?= $title ?>
</a>
