<?php /** @var \Snowdog\Menu\Block\NodeType\CustomUrl $block */ ?>
<?php
$class = $block->getMenuClass();
$dataAttribute = '';
$nodeLevel = $block->getLevel() + 1;
$hasChildren = $block->getIsParent();

if ($block->getIsViewAllLink()) {
    $title = __('View All');
    $classLink = $class . '__inner-link';
} else {
    $classLink = $block->getIsRoot() ? $class . '__link' : $class . '__inner-link';
    $title = $block->getTitle();
    if ($block->getId()) {
        $dataAttribute = ' data-menu="menu-' . $block->getId() . '"';
    }
}
?>
<a href="<?= $block->getContent() ?>"
   class="<?= $classLink ?>"<?= $dataAttribute ?>
>
    <?= $title ?>
    <?php if ($hasChildren && !$block->getIsViewAllLink()): ?>
        <?php if ($nodeLevel == 1): ?>
            <svg title="view more" class="<?= $class ?>__icon">
                <use xlink:href="<?= $block->getViewFileUrl('Snowdog_Menu::images/menu-icon-sprite.svg#icon-arrow-down') ?>"></use>
            </svg>
        <?php elseif ($nodeLevel != 1): ?>
            <svg title="view more" class="<?= $class ?>__icon <?= $class ?>__icon--inner">
                <use xlink:href="<?= $block->getViewFileUrl('Snowdog_Menu::images/menu-icon-sprite.svg#icon-plus') ?>"></use>
            </svg>
        <?php endif ?>
    <?php endif ?>
</a>
