<?php /** @var \Snowdog\Menu\Block\NodeType\CustomUrl $block */ ?>
<?php
$attributes = [];
$class = $block->getMenuClass();
$imageUrl = $block->getImageUrl();
$imageAltText = $block->getImageAltText();
$imageWidth = $block->getImageWidth();
$imageHeight = $block->getImageHeight();
$content = $block->getContent();

if ($block->getIsViewAllLink()) {
    $title = __('View All');
    $classLink = $class . '__inner-link';
} else {
    $classLink = $block->getIsRoot() ? $class . '__link' : $class . '__inner-link';
    $title = $block->getTitle();
    if ($block->getId()) {
        $attributes[] = 'data-menu="menu-' . $block->getId() . '"';
    }
}
$attributes[] = 'class="' . $classLink . '"';

if ($block->getTarget()) {
    $attributes[] = 'target="_blank" rel="noopener"';
}
$allAttributes = implode(' ', $attributes);
?>
<?php if ($content): ?>
    <a
        href="<?= $block->escapeUrl($content); ?>"
        <?= $allAttributes; ?>
    >
        <?= $block->escapeHtml($title); ?>
    </a>
<?php else: ?>
    <span
        <?= $allAttributes; ?>
        tabindex="0"
    >
        <?= $block->escapeHtml($title); ?>
    </span>
<?php endif; ?>

<?php if ($imageUrl): ?>
    <img
        src="<?= $block->escapeUrl($imageUrl); ?>"
        alt="<?= $block->escapeHtmlAttr($imageAltText); ?>"
        loading="lazy"
        width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>"
        height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>"
    />
<?php endif; ?>
