<?php /** @var \Snowdog\Menu\Block\NodeType\CmsPage $block */ ?>
<?php
$nodeId = $block->getId();
$pageUrl = $block->getPageUrl($nodeId) ?: '#';
$title = $block->getTitle();
$nodeClasses = $block->getNodeClasses();
?>

<a class="snowdog-menu-link <?= $escaper->escapeHtmlAttr($nodeClasses) ?>"
    href="<?= $escaper->escapeUrl($pageUrl) ?>"
    <?php if ($nodeId): ?>
        data-menu="menu-<?= $escaper->escapeHtmlAttr($nodeId) ?>"
    <?php endif; ?>
>
    <?= $escaper->escapeHtml($title) ?>
</a>
